---
title: "hw0429"
author: "Justin Hu"
date: "2019年4月29日"
output: html_document
---


```{r}
library(tidyverse)
library(lubridate)


# Excel Files
library(readxl)
library(writexl)
```

```{r}
# 2.0 Importing Files ----


bikes_tbl <- read_excel(path = "bikes.xlsx")

bikeshops_tbl <- read_excel("bikeshops.xlsx")

orderlines_tbl <- read_excel("orderlines.xlsx")
```

```{r}
# 3.0 Examining Data ----

bikes_tbl

glimpse(bikes_tbl)

bikeshops_tbl

orderlines_tbl
```

```{r}
# 4.0 Joining Data ----

#pipe

orderlines_bikes_tbl <- orderlines_tbl %>% left_join(bikes_tbl, by = c("product.id"="bike.id")) %>% 
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))  

?left_join

orderlines_tbl

bikes_tbl

left_join(orderlines_tbl, bikes_tbl, by = c("product.id" = "bike.id"))

bike_orderlines_joined_tbl <- orderlines_tbl %>%
    left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
    left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

bike_orderlines_joined_tbl

bike_orderlines_joined_tbl %>% glimpse()
```

```{r}
# 5.0 Wrangling Data ----

bike_orderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>%
    
    # Separate description into category.1, category.2, and frame.material
    separate(description,
             into = c("category.1", "category.2", "frame.material"),
             sep = " - ",
             remove = TRUE) %>%


    # Separate location into city and state
    separate(location,
             into = c("city", "state"),
             sep  = ", ",
             remove = FALSE) %>%

    
    # price extended
    mutate(total.price = price * quantity) %>%
    
    # Reorganize
    select(-...1, -location) %>%
    select(-ends_with(".id")) %>%
    
    bind_cols(bike_orderlines_joined_tbl %>% select(order.id)) %>%
    
    # Reorder columns
    select(contains("date"), contains("id"), contains("order"),
           quantity, price, total.price,
           everything()) %>%
    
    # Renaming columns
    rename(order_date = order.date) %>%
    set_names(names(.) %>% str_replace_all("\\.", "_")) 

bike_orderlines_wrangled_tbl %>% glimpse()
```